"""Capability protocols shared by Python hypergraph adapters."""

from .protocols import (
    MISSING,
    AllocatableHyperGraph,
    Capacity,
    ContiguousHyperEdgeIncidence,
    ContiguousNodeIncidence,
    Directedness,
    ExtendableHyperGraph,
    HyperEdgeCountable,
    HyperEdgeIncidence,
    HyperEdgeIndex,
    HyperEdgeList,
    HyperGraph,
    Missing,
    MutableIncidenceHyperGraph,
    NodeCountable,
    NodeIncidence,
    NodeIndex,
    NodeList,
    PropertyMapBase,
    PropertyMapError,
    PropertyMapKeyNotFoundError,
    PropertyMapReadable,
    PropertyMapReadWrite,
    PropertyMapWritable,
)

__all__ = [
    "MISSING",
    "AllocatableHyperGraph",
    "Capacity",
    "ContiguousHyperEdgeIncidence",
    "ContiguousNodeIncidence",
    "Directedness",
    "ExtendableHyperGraph",
    "HyperEdgeCountable",
    "HyperEdgeIncidence",
    "HyperEdgeIndex",
    "HyperEdgeList",
    "HyperGraph",
    "Missing",
    "MutableIncidenceHyperGraph",
    "NodeCountable",
    "NodeIncidence",
    "NodeIndex",
    "NodeList",
    "PropertyMapBase",
    "PropertyMapError",
    "PropertyMapKeyNotFoundError",
    "PropertyMapReadWrite",
    "PropertyMapReadable",
    "PropertyMapWritable",
]
