[project]
name = "hyperglue"
version = "0.1.0"
description = "Interoperability tools for the Python hypergraph ecosystem"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "gdown>=6.1.0",
    "hypergraphx",
    "hypernetx>=2.4.3",
    "juliacall>=0.9.35",
    "juliapkg[cli]>=0.1.26",
    "xgi>=0.10.2",
]

[dependency-groups]
dev = [
    "basedpyright>=1.39.10",
    "pytest>=9.1.1",
    "ruff>=0.16.4",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.uv.sources]
hypergraphx = { git = "https://github.com/viniciusdutra314/hypergraphx", branch = "hif_refactor" }

[build-system]
requires = ["uv_build>=0.11.0,<0.12.0"]
build-backend = "uv_build"
